### ISSUE TITLE
Box Type for Regexp

### ISSUE THREAD

**Issue by pplu** [alnewkirk/Data-Object#1]
Maybe it's feasable to have a box type for regexps? You could have operations like match, substitute, and methods that compose regexps together.

**Comment by alnewkirk** [comment]
@pplu This is definitely on the roadmap, tentatively. In the interim you could use something like [Regexp::Assembler](https://metacpan.org/pod/Regexp::Assemble).

**Comment by alnewkirk** [comment]
This issue is now being worked on - https://github.com/alnewkirk/Data-Object/pull/6.

**Comment by alnewkirk** [comment]
This feature has been implemented and is available on CPAN.
