### ISSUE TITLE
[Patch] Unescaped left brace in regex is deprecated

### ISSUE THREAD

**Issue by stevieb9** [alnewkirk/Data-Object#10]
This tiny patch eliminates the newer warning emitted in your Testers report (it wouldn't allow me to attach it).

<pre>
+++ Data-Object-0.53-new/t/prev/data/object/code/dump.t	2015-09-26 10:23:22.496894123 -0600
@@ -9,7 +9,7 @@
     my $code = Data::Object::Code->new(sub{1});
     my $dump = $code->dump;
     like $dump, qr/package Data::Object/;
-    like $dump, qr/goto \\\&{\$data;}/;
+    like $dump, qr/goto \\\&\{\$data;}/;
 };
 
 ok 1 and done_testing;
</pre>

**Comment by alnewkirk** [comment]
@stevieb9 Thanks for the report. This issue has been fixed in this commit https://github.com/alnewkirk/Data-Object/commit/4bb381fe870764b169f60fdfea7d2d18cb7f1445.
