### ISSUE TITLE
Array hashify could expect an optional sub

### ISSUE THREAD

**Issue by pplu** [alnewkirk/Data-Object#2]
An optional coderef could be passed to hashify so that the user controls the values.

```
# given [ 1,2,3,4 ]
$array->hashify( sub { shift % 2 } )
# yields { 1 => 1, 2 => 0, 3 => 1, 4 => 0 }
```

**Comment by alnewkirk** [comment]
Sounds good. I'll add this to the TODO for the next release.

**Comment by alnewkirk** [comment]
Feature implemented in ver. 0.12, commit https://github.com/alnewkirk/Data-Object/commit/39cab4ee51d2829a63e1c4dab038087ee99b31e6. Thanks.
